services:
  webfrontend:
     image: ${DOCKER_REGISTRY-}webfrontend
     depends_on:
        webapi:
          condition: service_healthy
     build:
        context: .
        dockerfile: WebFrontEnd/Dockerfile
     profiles:
        - donotstart

  webapi:
     image: ${DOCKER_REGISTRY-}webapi
     depends_on:
        redis:
          condition: service_started
        seq:
          condition: service_started
          
     healthcheck:
        test: curl --fail http://webapi:8080/healthz || exit 1
        interval: 20s
        timeout: 20s
        retries: 5
     build:
        context: .
        dockerfile: WebAPI/Dockerfile
     environment:
        CONNECTION_STRING: "Server=mysql;User=root;Password=${MYSQL_ROOT_PASSWORD};Database=TravianDb;AllowLoadLocalInfile=true"
        REDIS_URL: "redis:6379"
        REDIS_INSTANCE_NAME: "RedisTravian"
        AUTH0_AUTHORITY: ${AUTH0_AUTHORITY}
        AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
        AUTH0_DOMAIN: ${AUTH0_DOMAIN}
        AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
        AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
        OTEL_EXPORTER_OTLP_ENDPOINT: http://seq:5341/ingest/otlp/v1/traces
        OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf

  redis:
     image: redis
     command: ["redis-server", "--appendonly", "yes"]
     volumes:
        - redis_data:/data
  mysql:
     image: mysql
     environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     volumes:
        - mysql_data:/var/lib/mysql
  seq:
     image: datalust/seq
     ports: 
        - "5001:80"
     environment:
        ACCEPT_EULA: "Y"
        SEQ_API_CANONICALURI: "http://localhost:5001/"
     volumes:
        - seq_data:/data
volumes:
  redis_data:
  mysql_data:  
  seq_data: