@API_HostAddress = http://localhost:5297
@ServerName = france.x2.france.travian.com

GET {{API_HostAddress}}/servers/
Accept: application/json
###
GET {{API_HostAddress}}/servers/{{ServerName}}/players/170
Accept: application/json
###
GET {{API_HostAddress}}/servers/{{ServerName}}/villages/new/2026-04-21
Accept: application/json
###
GET {{API_HostAddress}}/servers/{{ServerName}}/players/deleted/2026-04-23
Accept: application/json
###
GET {{API_HostAddress}}/servers/{{ServerName}}/players/170/history/
Accept: application/json
###
GET {{API_HostAddress}}/health/ready
Accept: application/json

